<?php /**
 * Add ACF Blocks und Custom Fields
 * @return array
 */

add_action('acf/init', 'my_acf_init_block_types');
function my_acf_init_block_types() {

    // Bild und Text Block
    if( function_exists('acf_register_block_type') ) {

        acf_register_block_type(array(
            'name'              => 'title',
            'title'             => __('Bild und Text'),
            'description'       => __('Bild und Beschreibungstext für die Seite.'),
            'render_template'   => 'template-parts/blocks/image.php',
            'category'          => 'formatting',
            'icon'              => 'editor-underline',
            'keywords'          => array( 'Titel', 'quote' ),
        ));
        // Vergangene Veranstaltungen Block
        acf_register_block_type(array(
            'name'              => 'past_events',
            'title'             => __('Vergangene Veranstaltungen'),
            'description'       => __('Hier kannst du alle vergangenen Veranstaltungen einblenden lassen.'),
            'render_template'   => 'template-parts/blocks/past_events.php',
            'category'          => 'formatting',
            'icon'              => 'calendar            ',
            'keywords'          => array( 'Vergangene Veranstaltungen', 'quote' ),
        ));
        // Spielstätten Block
        acf_register_block_type(array(
            'name'              => 'venue',
            'title'             => __('Spielstätte mit Platzanzahl'),
            'description'       => __('Hier kannst du die Spielstätten auswählen, die angezeigt werden sollen.'),
            'render_template'   => 'template-parts/blocks/venue-list.php',
            'category'          => 'formatting',
            'icon'              => 'location',
            'keywords'          => array( 'Spielstätte', 'quote' ),
        ));
        // Kontaktdaten Block
        acf_register_block_type(array(
            'name'              => 'contact',
            'title'             => __('Kontaktdaten'),
            'description'       => __('Hier kannst du die Kontaktdaten hinterlegen, die angezeigt werden sollen.'),
            'render_template'   => 'template-parts/blocks/contact-card.php',
            'category'          => 'formatting',
            'icon'              => 'phone',
            'keywords'          => array( 'Kontakt', 'quote' ),
        ));
    };
}

if( function_exists('acf_add_local_field_group') ):

    acf_add_local_field_group(array(
        'key' => 'group_63fa9bd67f694',
        'title' => 'Bild und Text',
        'fields' => array(
            array(
                'key' => 'field_63fbd6312db2b',
                'label' => 'Überschrift',
                'name' => 'headline',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => 'Hier steht die Überschrift',
                'maxlength' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
            ),
            array(
                'key' => 'field_63fa9bd6b250d',
                'label' => 'Bild für die Seite',
                'name' => 'image',
                'aria-label' => '',
                'type' => 'image',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'return_format' => 'id',
                'library' => 'all',
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
                'preview_size' => 'medium',
            ),
            array(
                'key' => 'field_63fa9ca9b250e',
                'label' => 'Text für den Block',
                'name' => 'text',
                'aria-label' => '',
                'type' => 'textarea',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'maxlength' => '',
                'rows' => '',
                'placeholder' => '',
                'new_lines' => '',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'block',
                    'operator' => '==',
                    'value' => 'acf/title',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
        'show_in_rest' => 0,
    ));
    
    acf_add_local_field_group(array(
        'key' => 'group_63fbdb76c7f6d',
        'title' => 'Block Kontaktdaten',
        'fields' => array(
            array(
                'key' => 'field_63fbe8555dd9c',
                'label' => 'Kontaktdaten',
                'name' => 'contact_information',
                'aria-label' => '',
                'type' => 'repeater',
                'instructions' => 'Hier kannst du die Kontaktinformationen eintragen.',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'layout' => 'block',
                'pagination' => 0,
                'min' => 0,
                'max' => 0,
                'collapsed' => 'field_63fbdcbeba979',
                'button_label' => 'Weitere Person hinzufügen',
                'rows_per_page' => 20,
                'sub_fields' => array(
                    array(
                        'key' => 'field_63fbdcbeba979',
                        'label' => 'Name',
                        'name' => 'name',
                        'aria-label' => '',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'maxlength' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'parent_repeater' => 'field_63fbe8555dd9c',
                    ),
                    array(
                        'key' => 'field_63fbdcdd380c1',
                        'label' => 'Bild',
                        'name' => 'image',
                        'aria-label' => '',
                        'type' => 'image',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'return_format' => 'id',
                        'library' => 'all',
                        'min_width' => '',
                        'min_height' => '',
                        'min_size' => '',
                        'max_width' => '',
                        'max_height' => '',
                        'max_size' => '',
                        'mime_types' => '',
                        'preview_size' => 'medium',
                        'parent_repeater' => 'field_63fbe8555dd9c',
                    ),
                    array(
                        'key' => 'field_63fbdb76f5158',
                        'label' => 'Position',
                        'name' => 'position',
                        'aria-label' => '',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'maxlength' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'parent_repeater' => 'field_63fbe8555dd9c',
                    ),
                    array(
                        'key' => 'field_63fbdbb9f515a',
                        'label' => 'Telefonnummer',
                        'name' => 'phone',
                        'aria-label' => '',
                        'type' => 'number',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'min' => '',
                        'max' => '',
                        'placeholder' => '',
                        'step' => '',
                        'prepend' => '',
                        'append' => '',
                        'parent_repeater' => 'field_63fbe8555dd9c',
                    ),
                    array(
                        'key' => 'field_63fbdba6f5159',
                        'label' => 'E-Mail',
                        'name' => 'mail',
                        'aria-label' => '',
                        'type' => 'email',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'parent_repeater' => 'field_63fbe8555dd9c',
                    ),
                ),
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'block',
                    'operator' => '==',
                    'value' => 'acf/contact',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
        'show_in_rest' => 0,
    ));
    
    acf_add_local_field_group(array(
        'key' => 'group_63ed133762fbd',
        'title' => 'Spielstätten',
        'fields' => array(
            array(
                'key' => 'field_63ed13bed8119',
                'label' => 'Anzahl der Sitzplätze',
                'name' => 'seats',
                'aria-label' => '',
                'type' => 'number',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'min' => '',
                'max' => '',
                'placeholder' => '',
                'step' => '',
                'prepend' => '',
                'append' => '',
            ),
            array(
                'key' => 'field_63ed140ad811a',
                'label' => 'Adresse',
                'name' => 'adress',
                'aria-label' => '',
                'type' => 'textarea',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'maxlength' => '',
                'rows' => '',
                'placeholder' => '',
                'new_lines' => '',
            ),
            array(
                'key' => 'field_63ed14761fbc0',
                'label' => 'Bild der Spielstätte',
                'name' => 'venue_image',
                'aria-label' => '',
                'type' => 'image',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'return_format' => 'id',
                'library' => 'all',
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
                'preview_size' => 'medium',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'locations',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
        'show_in_rest' => 0,
    ));
    
    acf_add_local_field_group(array(
        'key' => 'group_63fa3b622e5a0',
        'title' => 'Übersicht Spielstätten',
        'fields' => array(
            array(
                'key' => 'field_63fa3b625b1a4',
                'label' => 'Spielstätten',
                'name' => 'venues',
                'aria-label' => '',
                'type' => 'post_object',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'post_type' => array(
                    0 => 'locations',
                ),
                'taxonomy' => '',
                'return_format' => 'object',
                'multiple' => 1,
                'allow_null' => 0,
                'ui' => 1,
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'block',
                    'operator' => '==',
                    'value' => 'acf/venue',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
        'show_in_rest' => 0,
    ));
    
    acf_add_local_field_group(array(
        'key' => 'group_63ed1512f0af1',
        'title' => 'Veranstaltungen',
        'fields' => array(
            array(
                'key' => 'field_63ed153286d1d',
                'label' => 'Beschreibung der Veranstaltung',
                'name' => 'event-description',
                'aria-label' => '',
                'type' => 'textarea',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'maxlength' => '',
                'rows' => '',
                'placeholder' => '',
                'new_lines' => '',
            ),
            array(
                'key' => 'field_63ed155686d1e',
                'label' => 'Datum der Veranstaltung',
                'name' => 'event-date',
                'aria-label' => '',
                'type' => 'date_picker',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'display_format' => 'd/m/Y',
                'return_format' => 'j. F Y',
                'first_day' => 1,
            ),
            array(
                'key' => 'field_63ed15bd86d1f',
                'label' => 'Uhrzeit der Veranstaltung',
                'name' => 'event-time',
                'aria-label' => '',
                'type' => 'time_picker',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'display_format' => 'g:i a',
                'return_format' => 'H:i',
            ),
            array(
                'key' => 'field_63ed15f386d21',
                'label' => 'Link zum Ticketverkauf',
                'name' => 'event-ticket',
                'aria-label' => '',
                'type' => 'url',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
            ),
            array(
                'key' => 'field_63ed15d686d20',
                'label' => 'Bild der Veranstaltung',
                'name' => 'event-image',
                'aria-label' => '',
                'type' => 'image',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'return_format' => 'id',
                'library' => 'all',
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
                'preview_size' => 'medium',
            ),
            array(
                'key' => 'field_63fa29d324ddb',
                'label' => 'Ort der Veranstaltung',
                'name' => 'event-location',
                'aria-label' => '',
                'type' => 'post_object',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'post_type' => array(
                    0 => 'locations',
                ),
                'taxonomy' => '',
                'return_format' => 'object',
                'multiple' => 0,
                'allow_null' => 0,
                'ui' => 1,
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'event',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'acf_after_title',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => array(
            0 => 'page_attributes',
        ),
        'active' => true,
        'description' => '',
        'show_in_rest' => 0,
    ));
    
    endif;		

/**
* Add ACF Block Überschrift und Bild
* @return array
*/




?>